highlighter: rouge
sass:
    style: compressed

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: # Required: replace this with your domain
name: fe.flag # Required: will be displayed on every page's header
title: Charles # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - 그렇게 긴 시간 동안에
  - 우리는 단 한 번 죽는다 - Molière
description: Son of Sokcho # Required

disqus:
  comments: false # Disabled - using utterances instead
  shortname: disqus

utterances:
  repo: feghi/feghi.github.io # Your GitHub repo for comments
  issue_term: pathname # Issues mapped by pathname
  theme: github-light # github-light, github-dark, preferred-color-scheme, etc.

google_analytics:
  id: "UA-176070257-1" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  Hannah_bada:
    output: true

exclude:
  - nul
  - vendor
  - Gemfile
  - Gemfile.lock
  - run_jekyll.bat
  - run_jekyll.ps1

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
